.TH LOOPS 1
.SH NAME
loops \- reports information on lists of numbers
.SH SYNOPSIS
.B loops
[\fIfile\fR]
.SH DESCRIPTION
.B loops
accepts lists of random numbers as input and reports the number of numbers, the
sum of all numbers, and the average of all numbers.
.SH BUGS
This program is not exceptionally robust.
